using System;
using System.Collections.Generic;
using LightJson;
using Unisave.Entities;

namespace Unisave.SteamMicrotransactions
{
    /// <summary>
    /// Represents a single steam microtransaction
    /// </summary>
    [EntityCollectionName("steam_microtransactions")]
    public class SteamTransactionEntity : Entity
    {
        /// <summary>
        /// State of the transaction
        /// </summary>
        public string State { get; set; }
            = SteamTransactionState.BeingPrepared;

        /// <summary>
        /// SteamID of the player that initiated the transaction
        /// </summary>
        public ulong PlayerSteamId { get; set; }

        /// <summary>
        /// ID of the entity of the unisave-authenticated player,
        /// obtained via Auth.Id() at the point when the transaction is first
        /// sent to the purchasing server.
        /// </summary>
        public string UnisavePlayerId { get; set; }

        /// <summary>
        /// Unique ID of the order. Generated when the transaction proposal
        /// reaches the purchasing server. Used by Steam to find the proper
        /// transaction during transaction finalization.
        /// </summary>
        public ulong OrderId { get; set; }

        /// <summary>
        /// Unique ID of the transaction
        /// (generated by steam when the transaction is initiated)
        /// </summary>
        public ulong TransactionId { get; set; }

        /// <summary>
        /// What language will item descriptions have.
        /// An ISO 639-1 language code.
        ///
        /// Supported languages:
        /// https://partner.steamgames.com/doc/store/localization/languages
        /// </summary>
        public string Language { get; set; }

        /// <summary>
        /// What currency are item prices in.
        /// An ISO 4217 currency code.
        ///
        /// Supported currencies:
        /// https://partner.steamgames.com/doc/store/pricing/currencies
        /// </summary>
        public string Currency { get; set; }

        /// <summary>
        /// Items that are being purchased by the player in the transaction
        /// </summary>
        public List<SteamTransactionItem> Items { get; set; }
            = new List<SteamTransactionItem>();

        /// <summary>
        /// Steam transaction error code, if an error was returned
        /// by the Steam API. The list of codes:
        /// https://partner.steamgames.com/doc/features/microtransactions/implementation#error_codes
        /// </summary>
        public string ErrorCode { get; set; }

        /// <summary>
        /// Description of the steam error, if an error was returned
        /// by the Steam API. The list of errors:
        /// https://partner.steamgames.com/doc/features/microtransactions/implementation#error_codes
        /// </summary>
        public string ErrorDescription { get; set; }
        
        /// <summary>
        /// Serialized exception if an unexpected code-exception was raised.
        /// Catches both server-side and client-side exceptions. Is null
        /// if no exception occured.
        /// </summary>
        public JsonObject Exception { get; set; }
        
        /// <summary>
        /// What the value of the State field was, when the exception
        /// was raised. Because exception transitions the state to "exception".
        /// Null if no exception occured.
        /// </summary>
        public string StateBeforeException { get; set; }

        /// <summary>
        /// Generates a random order ID uint value.
        /// </summary>
        public static ulong GenerateRandomOrderId()
        {
            var random = new Random();
            byte[] buf = new byte[8];
            random.NextBytes(buf);
            return BitConverter.ToUInt64(buf, 0);
        }

        /// <summary>
        /// Creates a new transaction entity as a proposed microtransaction
        /// into which items can be added, and it can then be sent to the server
        /// to be checked out.
        /// </summary>
        /// <param name="playerSteamId">
        /// ID of the currently logged-in Steam player
        /// </param>
        /// <param name="language">
        /// The language in which this transaction is going to be made
        /// </param>
        /// <param name="currency">
        /// The currency in which this transaction is going to be made
        /// </param>
        /// <returns>
        /// An in-memory instance of a SteamTransactionEntity that can be
        /// modified and then sent to the purchasing server to be completed.
        /// </returns>
        public static SteamTransactionEntity NewProposal(
            ulong playerSteamId,
            string language,
            string currency
        )
        {
            return new SteamTransactionEntity() {
                PlayerSteamId = playerSteamId,
                Language = language,
                Currency = currency
            };
        }

        /// <summary>
        /// Adds an item into the proposed transaction in the given quantity.
        /// </summary>
        /// <param name="productInfo">The product to be added.</param>
        /// <param name="quantity">The amount in which to add it.</param>
        /// <exception cref="ArgumentException"></exception>
        public void AddItem(LocalizedProductInfo productInfo, int quantity = 1)
        {
            if (EntityId != null)
                throw new InvalidOperationException(
                    "Items can only be added into a transaction proposal. " +
                    "This transaction entity has already been submitted to " +
                    "Steam and cannot therefore be modified."
                );
            
            if (quantity <= 0)
                throw new ArgumentException(
                    "Product quantity must be a positive integer."
                );
            
            if (productInfo.Currency != Currency)
                throw new ArgumentException(
                    "The given product is localized into a different " +
                    "currency than this transaction."
                );
            
            if (productInfo.Language != Language)
                throw new ArgumentException(
                    "The given product is localized into a different " +
                    "currency than this transaction."
                );

            Items.Add(new SteamTransactionItem(
                itemId: productInfo.ItemId,
                quantity: quantity,
                unitCost: productInfo.UnitCost,
                description: productInfo.Description,
                category: productInfo.Category,
                productTypeClassName: productInfo.ProductTypeClassName
            ));
        }
    }
}